//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiDressOnLineShop.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.AdditionalCity = new HashSet<AdditionalCity>();
            this.Products = new HashSet<Products>();
        }
    
        public string UserID { get; set; }
        public string CityID { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string TelNumber { get; set; }
        public string Email { get; set; }
        public string AdminID { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalCity> AdditionalCity { get; set; }
        public virtual Admin Admin { get; set; }
        public virtual City City { get; set; }
        public virtual UserCart UserCart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
